// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/blues120/ias-core/data/ent/activeinfo"
	"github.com/blues120/ias-core/data/ent/algorithm"
	"github.com/blues120/ias-core/data/ent/algorithmalarmtype"
	"github.com/blues120/ias-core/data/ent/camera"
	"github.com/blues120/ias-core/data/ent/device"
	"github.com/blues120/ias-core/data/ent/devicecamera"
	"github.com/blues120/ias-core/data/ent/devicetoken"
	"github.com/blues120/ias-core/data/ent/equipattr"
	"github.com/blues120/ias-core/data/ent/eventsubscription"
	"github.com/blues120/ias-core/data/ent/fileupload"
	"github.com/blues120/ias-core/data/ent/inform"
	"github.com/blues120/ias-core/data/ent/organization"
	"github.com/blues120/ias-core/data/ent/setting"
	"github.com/blues120/ias-core/data/ent/signature"
	"github.com/blues120/ias-core/data/ent/task"
	"github.com/blues120/ias-core/data/ent/taskcamera"
	"github.com/blues120/ias-core/data/ent/tasklimits"
	"github.com/blues120/ias-core/data/ent/upplatform"
	"github.com/blues120/ias-core/data/ent/user"
	"github.com/blues120/ias-core/data/ent/warningtype"
	"github.com/blues120/ias-core/data/ent/warnpush"
	"github.com/blues120/ias-core/data/ent/warnpushlog"
	"github.com/blues120/ias-core/data/ent/warnsmserr"
	"github.com/blues120/ias-core/data/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activeinfoMixin := schema.ActiveInfo{}.Mixin()
	activeinfoMixinHooks1 := activeinfoMixin[1].Hooks()
	activeinfo.Hooks[0] = activeinfoMixinHooks1[0]
	activeinfoMixinInters1 := activeinfoMixin[1].Interceptors()
	activeinfo.Interceptors[0] = activeinfoMixinInters1[0]
	activeinfoMixinFields0 := activeinfoMixin[0].Fields()
	_ = activeinfoMixinFields0
	activeinfoFields := schema.ActiveInfo{}.Fields()
	_ = activeinfoFields
	// activeinfoDescCreatedAt is the schema descriptor for created_at field.
	activeinfoDescCreatedAt := activeinfoMixinFields0[0].Descriptor()
	// activeinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	activeinfo.DefaultCreatedAt = activeinfoDescCreatedAt.Default.(func() time.Time)
	// activeinfoDescUpdatedAt is the schema descriptor for updated_at field.
	activeinfoDescUpdatedAt := activeinfoMixinFields0[1].Descriptor()
	// activeinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	activeinfo.DefaultUpdatedAt = activeinfoDescUpdatedAt.Default.(func() time.Time)
	// activeinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	activeinfo.UpdateDefaultUpdatedAt = activeinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	algorithmMixin := schema.Algorithm{}.Mixin()
	algorithmMixinHooks1 := algorithmMixin[1].Hooks()
	algorithm.Hooks[0] = algorithmMixinHooks1[0]
	algorithmMixinInters1 := algorithmMixin[1].Interceptors()
	algorithm.Interceptors[0] = algorithmMixinInters1[0]
	algorithmMixinFields0 := algorithmMixin[0].Fields()
	_ = algorithmMixinFields0
	algorithmFields := schema.Algorithm{}.Fields()
	_ = algorithmFields
	// algorithmDescCreatedAt is the schema descriptor for created_at field.
	algorithmDescCreatedAt := algorithmMixinFields0[0].Descriptor()
	// algorithm.DefaultCreatedAt holds the default value on creation for the created_at field.
	algorithm.DefaultCreatedAt = algorithmDescCreatedAt.Default.(func() time.Time)
	// algorithmDescUpdatedAt is the schema descriptor for updated_at field.
	algorithmDescUpdatedAt := algorithmMixinFields0[1].Descriptor()
	// algorithm.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	algorithm.DefaultUpdatedAt = algorithmDescUpdatedAt.Default.(func() time.Time)
	// algorithm.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	algorithm.UpdateDefaultUpdatedAt = algorithmDescUpdatedAt.UpdateDefault.(func() time.Time)
	// algorithmDescAvailable is the schema descriptor for available field.
	algorithmDescAvailable := algorithmFields[12].Descriptor()
	// algorithm.DefaultAvailable holds the default value on creation for the available field.
	algorithm.DefaultAvailable = algorithmDescAvailable.Default.(uint)
	// algorithmDescImage is the schema descriptor for image field.
	algorithmDescImage := algorithmFields[13].Descriptor()
	// algorithm.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	algorithm.ImageValidator = algorithmDescImage.Validators[0].(func(string) error)
	// algorithmDescLabelMap is the schema descriptor for label_map field.
	algorithmDescLabelMap := algorithmFields[14].Descriptor()
	// algorithm.LabelMapValidator is a validator for the "label_map" field. It is called by the builders before save.
	algorithm.LabelMapValidator = algorithmDescLabelMap.Validators[0].(func(string) error)
	// algorithmDescIsGroupType is the schema descriptor for is_group_type field.
	algorithmDescIsGroupType := algorithmFields[25].Descriptor()
	// algorithm.DefaultIsGroupType holds the default value on creation for the is_group_type field.
	algorithm.DefaultIsGroupType = algorithmDescIsGroupType.Default.(uint)
	algorithmalarmtypeMixin := schema.AlgorithmAlarmType{}.Mixin()
	algorithmalarmtypeMixinHooks1 := algorithmalarmtypeMixin[1].Hooks()
	algorithmalarmtype.Hooks[0] = algorithmalarmtypeMixinHooks1[0]
	algorithmalarmtypeMixinInters1 := algorithmalarmtypeMixin[1].Interceptors()
	algorithmalarmtype.Interceptors[0] = algorithmalarmtypeMixinInters1[0]
	algorithmalarmtypeMixinFields0 := algorithmalarmtypeMixin[0].Fields()
	_ = algorithmalarmtypeMixinFields0
	algorithmalarmtypeFields := schema.AlgorithmAlarmType{}.Fields()
	_ = algorithmalarmtypeFields
	// algorithmalarmtypeDescCreatedAt is the schema descriptor for created_at field.
	algorithmalarmtypeDescCreatedAt := algorithmalarmtypeMixinFields0[0].Descriptor()
	// algorithmalarmtype.DefaultCreatedAt holds the default value on creation for the created_at field.
	algorithmalarmtype.DefaultCreatedAt = algorithmalarmtypeDescCreatedAt.Default.(func() time.Time)
	// algorithmalarmtypeDescUpdatedAt is the schema descriptor for updated_at field.
	algorithmalarmtypeDescUpdatedAt := algorithmalarmtypeMixinFields0[1].Descriptor()
	// algorithmalarmtype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	algorithmalarmtype.DefaultUpdatedAt = algorithmalarmtypeDescUpdatedAt.Default.(func() time.Time)
	// algorithmalarmtype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	algorithmalarmtype.UpdateDefaultUpdatedAt = algorithmalarmtypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// algorithmalarmtypeDescTypeName is the schema descriptor for type_name field.
	algorithmalarmtypeDescTypeName := algorithmalarmtypeFields[1].Descriptor()
	// algorithmalarmtype.DefaultTypeName holds the default value on creation for the type_name field.
	algorithmalarmtype.DefaultTypeName = algorithmalarmtypeDescTypeName.Default.(string)
	// algorithmalarmtype.TypeNameValidator is a validator for the "type_name" field. It is called by the builders before save.
	algorithmalarmtype.TypeNameValidator = algorithmalarmtypeDescTypeName.Validators[0].(func(string) error)
	cameraMixin := schema.Camera{}.Mixin()
	cameraMixinHooks1 := cameraMixin[1].Hooks()
	cameraMixinHooks2 := cameraMixin[2].Hooks()
	cameraMixinHooks3 := cameraMixin[3].Hooks()
	camera.Hooks[0] = cameraMixinHooks1[0]
	camera.Hooks[1] = cameraMixinHooks2[0]
	camera.Hooks[2] = cameraMixinHooks2[1]
	camera.Hooks[3] = cameraMixinHooks3[0]
	camera.Hooks[4] = cameraMixinHooks3[1]
	cameraMixinInters1 := cameraMixin[1].Interceptors()
	cameraMixinInters2 := cameraMixin[2].Interceptors()
	cameraMixinInters3 := cameraMixin[3].Interceptors()
	cameraInters := schema.Camera{}.Interceptors()
	camera.Interceptors[0] = cameraMixinInters1[0]
	camera.Interceptors[1] = cameraMixinInters2[0]
	camera.Interceptors[2] = cameraMixinInters3[0]
	camera.Interceptors[3] = cameraInters[0]
	cameraMixinFields0 := cameraMixin[0].Fields()
	_ = cameraMixinFields0
	cameraFields := schema.Camera{}.Fields()
	_ = cameraFields
	// cameraDescCreatedAt is the schema descriptor for created_at field.
	cameraDescCreatedAt := cameraMixinFields0[0].Descriptor()
	// camera.DefaultCreatedAt holds the default value on creation for the created_at field.
	camera.DefaultCreatedAt = cameraDescCreatedAt.Default.(func() time.Time)
	// cameraDescUpdatedAt is the schema descriptor for updated_at field.
	cameraDescUpdatedAt := cameraMixinFields0[1].Descriptor()
	// camera.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	camera.DefaultUpdatedAt = cameraDescUpdatedAt.Default.(func() time.Time)
	// camera.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	camera.UpdateDefaultUpdatedAt = cameraDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cameraDescPlace is the schema descriptor for place field.
	cameraDescPlace := cameraFields[13].Descriptor()
	// camera.DefaultPlace holds the default value on creation for the place field.
	camera.DefaultPlace = cameraDescPlace.Default.(string)
	// cameraDescSpSource is the schema descriptor for sp_source field.
	cameraDescSpSource := cameraFields[16].Descriptor()
	// camera.SpSourceValidator is a validator for the "sp_source" field. It is called by the builders before save.
	camera.SpSourceValidator = cameraDescSpSource.Validators[0].(func(string) error)
	// cameraDescTransType is the schema descriptor for trans_type field.
	cameraDescTransType := cameraFields[20].Descriptor()
	// camera.DefaultTransType holds the default value on creation for the trans_type field.
	camera.DefaultTransType = cameraDescTransType.Default.(string)
	// cameraDescDeviceIP is the schema descriptor for device_ip field.
	cameraDescDeviceIP := cameraFields[21].Descriptor()
	// camera.DefaultDeviceIP holds the default value on creation for the device_ip field.
	camera.DefaultDeviceIP = cameraDescDeviceIP.Default.(string)
	// cameraDescDevicePort is the schema descriptor for device_port field.
	cameraDescDevicePort := cameraFields[22].Descriptor()
	// camera.DefaultDevicePort holds the default value on creation for the device_port field.
	camera.DefaultDevicePort = cameraDescDevicePort.Default.(int32)
	// cameraDescGBID is the schema descriptor for gb_id field.
	cameraDescGBID := cameraFields[23].Descriptor()
	// camera.DefaultGBID holds the default value on creation for the gb_id field.
	camera.DefaultGBID = cameraDescGBID.Default.(string)
	// cameraDescSipUser is the schema descriptor for sip_user field.
	cameraDescSipUser := cameraFields[24].Descriptor()
	// camera.DefaultSipUser holds the default value on creation for the sip_user field.
	camera.DefaultSipUser = cameraDescSipUser.Default.(string)
	// cameraDescSipPassword is the schema descriptor for sip_password field.
	cameraDescSipPassword := cameraFields[25].Descriptor()
	// camera.DefaultSipPassword holds the default value on creation for the sip_password field.
	camera.DefaultSipPassword = cameraDescSipPassword.Default.(string)
	// cameraDescGBChannelID is the schema descriptor for gb_channel_id field.
	cameraDescGBChannelID := cameraFields[26].Descriptor()
	// camera.DefaultGBChannelID holds the default value on creation for the gb_channel_id field.
	camera.DefaultGBChannelID = cameraDescGBChannelID.Default.(string)
	// cameraDescUpGBChannelID is the schema descriptor for up_gb_channel_id field.
	cameraDescUpGBChannelID := cameraFields[27].Descriptor()
	// camera.DefaultUpGBChannelID holds the default value on creation for the up_gb_channel_id field.
	camera.DefaultUpGBChannelID = cameraDescUpGBChannelID.Default.(string)
	// cameraDescGBDeviceType is the schema descriptor for gb_device_type field.
	cameraDescGBDeviceType := cameraFields[28].Descriptor()
	// camera.DefaultGBDeviceType holds the default value on creation for the gb_device_type field.
	camera.DefaultGBDeviceType = cameraDescGBDeviceType.Default.(string)
	deviceMixin := schema.Device{}.Mixin()
	deviceMixinHooks1 := deviceMixin[1].Hooks()
	deviceMixinHooks2 := deviceMixin[2].Hooks()
	deviceMixinHooks3 := deviceMixin[3].Hooks()
	device.Hooks[0] = deviceMixinHooks1[0]
	device.Hooks[1] = deviceMixinHooks2[0]
	device.Hooks[2] = deviceMixinHooks2[1]
	device.Hooks[3] = deviceMixinHooks3[0]
	device.Hooks[4] = deviceMixinHooks3[1]
	deviceMixinInters1 := deviceMixin[1].Interceptors()
	deviceMixinInters2 := deviceMixin[2].Interceptors()
	deviceMixinInters3 := deviceMixin[3].Interceptors()
	deviceInters := schema.Device{}.Interceptors()
	device.Interceptors[0] = deviceMixinInters1[0]
	device.Interceptors[1] = deviceMixinInters2[0]
	device.Interceptors[2] = deviceMixinInters3[0]
	device.Interceptors[3] = deviceInters[0]
	deviceMixinFields0 := deviceMixin[0].Fields()
	_ = deviceMixinFields0
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceMixinFields0[0].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceMixinFields0[1].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	devicecameraMixin := schema.DeviceCamera{}.Mixin()
	devicecameraMixinFields0 := devicecameraMixin[0].Fields()
	_ = devicecameraMixinFields0
	devicecameraFields := schema.DeviceCamera{}.Fields()
	_ = devicecameraFields
	// devicecameraDescCreatedAt is the schema descriptor for created_at field.
	devicecameraDescCreatedAt := devicecameraMixinFields0[0].Descriptor()
	// devicecamera.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicecamera.DefaultCreatedAt = devicecameraDescCreatedAt.Default.(func() time.Time)
	// devicecameraDescUpdatedAt is the schema descriptor for updated_at field.
	devicecameraDescUpdatedAt := devicecameraMixinFields0[1].Descriptor()
	// devicecamera.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	devicecamera.DefaultUpdatedAt = devicecameraDescUpdatedAt.Default.(func() time.Time)
	// devicecamera.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	devicecamera.UpdateDefaultUpdatedAt = devicecameraDescUpdatedAt.UpdateDefault.(func() time.Time)
	devicetokenMixin := schema.DeviceToken{}.Mixin()
	devicetokenMixinHooks1 := devicetokenMixin[1].Hooks()
	devicetoken.Hooks[0] = devicetokenMixinHooks1[0]
	devicetokenMixinInters1 := devicetokenMixin[1].Interceptors()
	devicetoken.Interceptors[0] = devicetokenMixinInters1[0]
	devicetokenMixinFields0 := devicetokenMixin[0].Fields()
	_ = devicetokenMixinFields0
	devicetokenFields := schema.DeviceToken{}.Fields()
	_ = devicetokenFields
	// devicetokenDescCreatedAt is the schema descriptor for created_at field.
	devicetokenDescCreatedAt := devicetokenMixinFields0[0].Descriptor()
	// devicetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicetoken.DefaultCreatedAt = devicetokenDescCreatedAt.Default.(func() time.Time)
	// devicetokenDescUpdatedAt is the schema descriptor for updated_at field.
	devicetokenDescUpdatedAt := devicetokenMixinFields0[1].Descriptor()
	// devicetoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	devicetoken.DefaultUpdatedAt = devicetokenDescUpdatedAt.Default.(func() time.Time)
	// devicetoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	devicetoken.UpdateDefaultUpdatedAt = devicetokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	equipattrMixin := schema.EquipAttr{}.Mixin()
	equipattrMixinHooks1 := equipattrMixin[1].Hooks()
	equipattr.Hooks[0] = equipattrMixinHooks1[0]
	equipattrMixinInters1 := equipattrMixin[1].Interceptors()
	equipattr.Interceptors[0] = equipattrMixinInters1[0]
	equipattrMixinFields0 := equipattrMixin[0].Fields()
	_ = equipattrMixinFields0
	equipattrFields := schema.EquipAttr{}.Fields()
	_ = equipattrFields
	// equipattrDescCreatedAt is the schema descriptor for created_at field.
	equipattrDescCreatedAt := equipattrMixinFields0[0].Descriptor()
	// equipattr.DefaultCreatedAt holds the default value on creation for the created_at field.
	equipattr.DefaultCreatedAt = equipattrDescCreatedAt.Default.(func() time.Time)
	// equipattrDescUpdatedAt is the schema descriptor for updated_at field.
	equipattrDescUpdatedAt := equipattrMixinFields0[1].Descriptor()
	// equipattr.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipattr.DefaultUpdatedAt = equipattrDescUpdatedAt.Default.(func() time.Time)
	// equipattr.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipattr.UpdateDefaultUpdatedAt = equipattrDescUpdatedAt.UpdateDefault.(func() time.Time)
	eventsubscriptionMixin := schema.EventSubscription{}.Mixin()
	eventsubscriptionMixinHooks1 := eventsubscriptionMixin[1].Hooks()
	eventsubscription.Hooks[0] = eventsubscriptionMixinHooks1[0]
	eventsubscriptionMixinInters1 := eventsubscriptionMixin[1].Interceptors()
	eventsubscription.Interceptors[0] = eventsubscriptionMixinInters1[0]
	eventsubscriptionMixinFields0 := eventsubscriptionMixin[0].Fields()
	_ = eventsubscriptionMixinFields0
	eventsubscriptionFields := schema.EventSubscription{}.Fields()
	_ = eventsubscriptionFields
	// eventsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	eventsubscriptionDescCreatedAt := eventsubscriptionMixinFields0[0].Descriptor()
	// eventsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	eventsubscription.DefaultCreatedAt = eventsubscriptionDescCreatedAt.Default.(func() time.Time)
	// eventsubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	eventsubscriptionDescUpdatedAt := eventsubscriptionMixinFields0[1].Descriptor()
	// eventsubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	eventsubscription.DefaultUpdatedAt = eventsubscriptionDescUpdatedAt.Default.(func() time.Time)
	// eventsubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	eventsubscription.UpdateDefaultUpdatedAt = eventsubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	fileuploadMixin := schema.FileUpload{}.Mixin()
	fileuploadMixinHooks1 := fileuploadMixin[1].Hooks()
	fileupload.Hooks[0] = fileuploadMixinHooks1[0]
	fileuploadMixinInters1 := fileuploadMixin[1].Interceptors()
	fileupload.Interceptors[0] = fileuploadMixinInters1[0]
	fileuploadMixinFields0 := fileuploadMixin[0].Fields()
	_ = fileuploadMixinFields0
	fileuploadFields := schema.FileUpload{}.Fields()
	_ = fileuploadFields
	// fileuploadDescCreatedAt is the schema descriptor for created_at field.
	fileuploadDescCreatedAt := fileuploadMixinFields0[0].Descriptor()
	// fileupload.DefaultCreatedAt holds the default value on creation for the created_at field.
	fileupload.DefaultCreatedAt = fileuploadDescCreatedAt.Default.(func() time.Time)
	// fileuploadDescUpdatedAt is the schema descriptor for updated_at field.
	fileuploadDescUpdatedAt := fileuploadMixinFields0[1].Descriptor()
	// fileupload.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fileupload.DefaultUpdatedAt = fileuploadDescUpdatedAt.Default.(func() time.Time)
	// fileupload.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fileupload.UpdateDefaultUpdatedAt = fileuploadDescUpdatedAt.UpdateDefault.(func() time.Time)
	informMixin := schema.Inform{}.Mixin()
	informMixinHooks0 := informMixin[0].Hooks()
	informMixinHooks1 := informMixin[1].Hooks()
	inform.Hooks[0] = informMixinHooks0[0]
	inform.Hooks[1] = informMixinHooks0[1]
	inform.Hooks[2] = informMixinHooks1[0]
	inform.Hooks[3] = informMixinHooks1[1]
	informMixinInters0 := informMixin[0].Interceptors()
	informMixinInters1 := informMixin[1].Interceptors()
	inform.Interceptors[0] = informMixinInters0[0]
	inform.Interceptors[1] = informMixinInters1[0]
	organizationMixin := schema.Organization{}.Mixin()
	organizationMixinHooks1 := organizationMixin[1].Hooks()
	organization.Hooks[0] = organizationMixinHooks1[0]
	organizationMixinInters1 := organizationMixin[1].Interceptors()
	organization.Interceptors[0] = organizationMixinInters1[0]
	organizationMixinFields0 := organizationMixin[0].Fields()
	_ = organizationMixinFields0
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationMixinFields0[0].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationMixinFields0[1].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescIamRoleID is the schema descriptor for iam_role_id field.
	organizationDescIamRoleID := organizationFields[3].Descriptor()
	// organization.DefaultIamRoleID holds the default value on creation for the iam_role_id field.
	organization.DefaultIamRoleID = organizationDescIamRoleID.Default.(string)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescWorkspaceID is the schema descriptor for workspace_id field.
	settingDescWorkspaceID := settingFields[5].Descriptor()
	// setting.DefaultWorkspaceID holds the default value on creation for the workspace_id field.
	setting.DefaultWorkspaceID = settingDescWorkspaceID.Default.(string)
	signatureMixin := schema.Signature{}.Mixin()
	signatureMixinHooks1 := signatureMixin[1].Hooks()
	signature.Hooks[0] = signatureMixinHooks1[0]
	signatureMixinInters1 := signatureMixin[1].Interceptors()
	signature.Interceptors[0] = signatureMixinInters1[0]
	signatureMixinFields0 := signatureMixin[0].Fields()
	_ = signatureMixinFields0
	signatureFields := schema.Signature{}.Fields()
	_ = signatureFields
	// signatureDescCreatedAt is the schema descriptor for created_at field.
	signatureDescCreatedAt := signatureMixinFields0[0].Descriptor()
	// signature.DefaultCreatedAt holds the default value on creation for the created_at field.
	signature.DefaultCreatedAt = signatureDescCreatedAt.Default.(func() time.Time)
	// signatureDescUpdatedAt is the schema descriptor for updated_at field.
	signatureDescUpdatedAt := signatureMixinFields0[1].Descriptor()
	// signature.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	signature.DefaultUpdatedAt = signatureDescUpdatedAt.Default.(func() time.Time)
	// signature.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	signature.UpdateDefaultUpdatedAt = signatureDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskMixin := schema.Task{}.Mixin()
	taskMixinHooks1 := taskMixin[1].Hooks()
	taskMixinHooks2 := taskMixin[2].Hooks()
	taskMixinHooks3 := taskMixin[3].Hooks()
	task.Hooks[0] = taskMixinHooks1[0]
	task.Hooks[1] = taskMixinHooks2[0]
	task.Hooks[2] = taskMixinHooks2[1]
	task.Hooks[3] = taskMixinHooks3[0]
	task.Hooks[4] = taskMixinHooks3[1]
	taskMixinInters1 := taskMixin[1].Interceptors()
	taskMixinInters2 := taskMixin[2].Interceptors()
	taskMixinInters3 := taskMixin[3].Interceptors()
	taskInters := schema.Task{}.Interceptors()
	task.Interceptors[0] = taskMixinInters1[0]
	task.Interceptors[1] = taskMixinInters2[0]
	task.Interceptors[2] = taskMixinInters3[0]
	task.Interceptors[3] = taskInters[0]
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescReason is the schema descriptor for reason field.
	taskDescReason := taskFields[15].Descriptor()
	// task.DefaultReason holds the default value on creation for the reason field.
	task.DefaultReason = taskDescReason.Default.(string)
	taskcameraMixin := schema.TaskCamera{}.Mixin()
	taskcameraMixinHooks1 := taskcameraMixin[1].Hooks()
	taskcameraMixinHooks2 := taskcameraMixin[2].Hooks()
	taskcamera.Hooks[0] = taskcameraMixinHooks1[0]
	taskcamera.Hooks[1] = taskcameraMixinHooks1[1]
	taskcamera.Hooks[2] = taskcameraMixinHooks2[0]
	taskcamera.Hooks[3] = taskcameraMixinHooks2[1]
	taskcameraMixinInters1 := taskcameraMixin[1].Interceptors()
	taskcameraMixinInters2 := taskcameraMixin[2].Interceptors()
	taskcamera.Interceptors[0] = taskcameraMixinInters1[0]
	taskcamera.Interceptors[1] = taskcameraMixinInters2[0]
	taskcameraMixinFields0 := taskcameraMixin[0].Fields()
	_ = taskcameraMixinFields0
	taskcameraFields := schema.TaskCamera{}.Fields()
	_ = taskcameraFields
	// taskcameraDescCreatedAt is the schema descriptor for created_at field.
	taskcameraDescCreatedAt := taskcameraMixinFields0[0].Descriptor()
	// taskcamera.DefaultCreatedAt holds the default value on creation for the created_at field.
	taskcamera.DefaultCreatedAt = taskcameraDescCreatedAt.Default.(func() time.Time)
	// taskcameraDescUpdatedAt is the schema descriptor for updated_at field.
	taskcameraDescUpdatedAt := taskcameraMixinFields0[1].Descriptor()
	// taskcamera.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	taskcamera.DefaultUpdatedAt = taskcameraDescUpdatedAt.Default.(func() time.Time)
	// taskcamera.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	taskcamera.UpdateDefaultUpdatedAt = taskcameraDescUpdatedAt.UpdateDefault.(func() time.Time)
	tasklimitsMixin := schema.TaskLimits{}.Mixin()
	tasklimitsMixinHooks1 := tasklimitsMixin[1].Hooks()
	tasklimits.Hooks[0] = tasklimitsMixinHooks1[0]
	tasklimitsMixinInters1 := tasklimitsMixin[1].Interceptors()
	tasklimits.Interceptors[0] = tasklimitsMixinInters1[0]
	tasklimitsMixinFields0 := tasklimitsMixin[0].Fields()
	_ = tasklimitsMixinFields0
	tasklimitsFields := schema.TaskLimits{}.Fields()
	_ = tasklimitsFields
	// tasklimitsDescCreatedAt is the schema descriptor for created_at field.
	tasklimitsDescCreatedAt := tasklimitsMixinFields0[0].Descriptor()
	// tasklimits.DefaultCreatedAt holds the default value on creation for the created_at field.
	tasklimits.DefaultCreatedAt = tasklimitsDescCreatedAt.Default.(func() time.Time)
	// tasklimitsDescUpdatedAt is the schema descriptor for updated_at field.
	tasklimitsDescUpdatedAt := tasklimitsMixinFields0[1].Descriptor()
	// tasklimits.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tasklimits.DefaultUpdatedAt = tasklimitsDescUpdatedAt.Default.(func() time.Time)
	// tasklimits.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tasklimits.UpdateDefaultUpdatedAt = tasklimitsDescUpdatedAt.UpdateDefault.(func() time.Time)
	upplatformMixin := schema.UpPlatform{}.Mixin()
	upplatformMixinHooks0 := upplatformMixin[0].Hooks()
	upplatformMixinHooks1 := upplatformMixin[1].Hooks()
	upplatform.Hooks[0] = upplatformMixinHooks0[0]
	upplatform.Hooks[1] = upplatformMixinHooks0[1]
	upplatform.Hooks[2] = upplatformMixinHooks1[0]
	upplatform.Hooks[3] = upplatformMixinHooks1[1]
	upplatformMixinInters0 := upplatformMixin[0].Interceptors()
	upplatformMixinInters1 := upplatformMixin[1].Interceptors()
	upplatform.Interceptors[0] = upplatformMixinInters0[0]
	upplatform.Interceptors[1] = upplatformMixinInters1[0]
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	warnpushMixin := schema.WarnPush{}.Mixin()
	warnpushMixinHooks1 := warnpushMixin[1].Hooks()
	warnpushMixinHooks2 := warnpushMixin[2].Hooks()
	warnpushMixinHooks3 := warnpushMixin[3].Hooks()
	warnpush.Hooks[0] = warnpushMixinHooks1[0]
	warnpush.Hooks[1] = warnpushMixinHooks2[0]
	warnpush.Hooks[2] = warnpushMixinHooks2[1]
	warnpush.Hooks[3] = warnpushMixinHooks3[0]
	warnpush.Hooks[4] = warnpushMixinHooks3[1]
	warnpushMixinInters1 := warnpushMixin[1].Interceptors()
	warnpushMixinInters2 := warnpushMixin[2].Interceptors()
	warnpushMixinInters3 := warnpushMixin[3].Interceptors()
	warnpush.Interceptors[0] = warnpushMixinInters1[0]
	warnpush.Interceptors[1] = warnpushMixinInters2[0]
	warnpush.Interceptors[2] = warnpushMixinInters3[0]
	warnpushMixinFields0 := warnpushMixin[0].Fields()
	_ = warnpushMixinFields0
	warnpushFields := schema.WarnPush{}.Fields()
	_ = warnpushFields
	// warnpushDescCreatedAt is the schema descriptor for created_at field.
	warnpushDescCreatedAt := warnpushMixinFields0[0].Descriptor()
	// warnpush.DefaultCreatedAt holds the default value on creation for the created_at field.
	warnpush.DefaultCreatedAt = warnpushDescCreatedAt.Default.(func() time.Time)
	// warnpushDescUpdatedAt is the schema descriptor for updated_at field.
	warnpushDescUpdatedAt := warnpushMixinFields0[1].Descriptor()
	// warnpush.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	warnpush.DefaultUpdatedAt = warnpushDescUpdatedAt.Default.(func() time.Time)
	// warnpush.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	warnpush.UpdateDefaultUpdatedAt = warnpushDescUpdatedAt.UpdateDefault.(func() time.Time)
	warnpushlogMixin := schema.WarnPushLog{}.Mixin()
	warnpushlogMixinHooks1 := warnpushlogMixin[1].Hooks()
	warnpushlogMixinHooks2 := warnpushlogMixin[2].Hooks()
	warnpushlogMixinHooks3 := warnpushlogMixin[3].Hooks()
	warnpushlog.Hooks[0] = warnpushlogMixinHooks1[0]
	warnpushlog.Hooks[1] = warnpushlogMixinHooks2[0]
	warnpushlog.Hooks[2] = warnpushlogMixinHooks2[1]
	warnpushlog.Hooks[3] = warnpushlogMixinHooks3[0]
	warnpushlog.Hooks[4] = warnpushlogMixinHooks3[1]
	warnpushlogMixinInters1 := warnpushlogMixin[1].Interceptors()
	warnpushlogMixinInters2 := warnpushlogMixin[2].Interceptors()
	warnpushlogMixinInters3 := warnpushlogMixin[3].Interceptors()
	warnpushlog.Interceptors[0] = warnpushlogMixinInters1[0]
	warnpushlog.Interceptors[1] = warnpushlogMixinInters2[0]
	warnpushlog.Interceptors[2] = warnpushlogMixinInters3[0]
	warnpushlogMixinFields0 := warnpushlogMixin[0].Fields()
	_ = warnpushlogMixinFields0
	warnpushlogFields := schema.WarnPushLog{}.Fields()
	_ = warnpushlogFields
	// warnpushlogDescCreatedAt is the schema descriptor for created_at field.
	warnpushlogDescCreatedAt := warnpushlogMixinFields0[0].Descriptor()
	// warnpushlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	warnpushlog.DefaultCreatedAt = warnpushlogDescCreatedAt.Default.(func() time.Time)
	// warnpushlogDescUpdatedAt is the schema descriptor for updated_at field.
	warnpushlogDescUpdatedAt := warnpushlogMixinFields0[1].Descriptor()
	// warnpushlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	warnpushlog.DefaultUpdatedAt = warnpushlogDescUpdatedAt.Default.(func() time.Time)
	// warnpushlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	warnpushlog.UpdateDefaultUpdatedAt = warnpushlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	warnsmserrMixin := schema.WarnSmsErr{}.Mixin()
	warnsmserrMixinHooks1 := warnsmserrMixin[1].Hooks()
	warnsmserrMixinHooks2 := warnsmserrMixin[2].Hooks()
	warnsmserr.Hooks[0] = warnsmserrMixinHooks1[0]
	warnsmserr.Hooks[1] = warnsmserrMixinHooks1[1]
	warnsmserr.Hooks[2] = warnsmserrMixinHooks2[0]
	warnsmserr.Hooks[3] = warnsmserrMixinHooks2[1]
	warnsmserrMixinInters1 := warnsmserrMixin[1].Interceptors()
	warnsmserrMixinInters2 := warnsmserrMixin[2].Interceptors()
	warnsmserr.Interceptors[0] = warnsmserrMixinInters1[0]
	warnsmserr.Interceptors[1] = warnsmserrMixinInters2[0]
	warnsmserrMixinFields0 := warnsmserrMixin[0].Fields()
	_ = warnsmserrMixinFields0
	warnsmserrFields := schema.WarnSmsErr{}.Fields()
	_ = warnsmserrFields
	// warnsmserrDescCreatedAt is the schema descriptor for created_at field.
	warnsmserrDescCreatedAt := warnsmserrMixinFields0[0].Descriptor()
	// warnsmserr.DefaultCreatedAt holds the default value on creation for the created_at field.
	warnsmserr.DefaultCreatedAt = warnsmserrDescCreatedAt.Default.(func() time.Time)
	// warnsmserrDescUpdatedAt is the schema descriptor for updated_at field.
	warnsmserrDescUpdatedAt := warnsmserrMixinFields0[1].Descriptor()
	// warnsmserr.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	warnsmserr.DefaultUpdatedAt = warnsmserrDescUpdatedAt.Default.(func() time.Time)
	// warnsmserr.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	warnsmserr.UpdateDefaultUpdatedAt = warnsmserrDescUpdatedAt.UpdateDefault.(func() time.Time)
	warningtypeMixin := schema.WarningType{}.Mixin()
	warningtypeMixinHooks1 := warningtypeMixin[1].Hooks()
	warningtype.Hooks[0] = warningtypeMixinHooks1[0]
	warningtypeMixinInters1 := warningtypeMixin[1].Interceptors()
	warningtype.Interceptors[0] = warningtypeMixinInters1[0]
	warningtypeMixinFields0 := warningtypeMixin[0].Fields()
	_ = warningtypeMixinFields0
	warningtypeFields := schema.WarningType{}.Fields()
	_ = warningtypeFields
	// warningtypeDescCreatedAt is the schema descriptor for created_at field.
	warningtypeDescCreatedAt := warningtypeMixinFields0[0].Descriptor()
	// warningtype.DefaultCreatedAt holds the default value on creation for the created_at field.
	warningtype.DefaultCreatedAt = warningtypeDescCreatedAt.Default.(func() time.Time)
	// warningtypeDescUpdatedAt is the schema descriptor for updated_at field.
	warningtypeDescUpdatedAt := warningtypeMixinFields0[1].Descriptor()
	// warningtype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	warningtype.DefaultUpdatedAt = warningtypeDescUpdatedAt.Default.(func() time.Time)
	// warningtype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	warningtype.UpdateDefaultUpdatedAt = warningtypeDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.12.5"                                         // Version of ent codegen.
	Sum     = "h1:KREM5E4CSoej4zeGa88Ou/gfturAnpUv0mzAjch1sj4=" // Sum of ent codegen.
)
