// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blues120/ias-core/data/ent/algorithm"
	"github.com/blues120/ias-core/data/ent/predicate"
	"github.com/blues120/ias-core/data/ent/task"
)

// AlgorithmQuery is the builder for querying Algorithm entities.
type AlgorithmQuery struct {
	config
	ctx        *QueryContext
	order      []algorithm.OrderOption
	inters     []Interceptor
	predicates []predicate.Algorithm
	withTasks  *TaskQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlgorithmQuery builder.
func (aq *AlgorithmQuery) Where(ps ...predicate.Algorithm) *AlgorithmQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AlgorithmQuery) Limit(limit int) *AlgorithmQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AlgorithmQuery) Offset(offset int) *AlgorithmQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AlgorithmQuery) Unique(unique bool) *AlgorithmQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AlgorithmQuery) Order(o ...algorithm.OrderOption) *AlgorithmQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryTasks chains the current query on the "tasks" edge.
func (aq *AlgorithmQuery) QueryTasks() *TaskQuery {
	query := (&TaskClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(algorithm.Table, algorithm.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, algorithm.TasksTable, algorithm.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Algorithm entity from the query.
// Returns a *NotFoundError when no Algorithm was found.
func (aq *AlgorithmQuery) First(ctx context.Context) (*Algorithm, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{algorithm.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AlgorithmQuery) FirstX(ctx context.Context) *Algorithm {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Algorithm ID from the query.
// Returns a *NotFoundError when no Algorithm ID was found.
func (aq *AlgorithmQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{algorithm.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AlgorithmQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Algorithm entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Algorithm entity is found.
// Returns a *NotFoundError when no Algorithm entities are found.
func (aq *AlgorithmQuery) Only(ctx context.Context) (*Algorithm, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{algorithm.Label}
	default:
		return nil, &NotSingularError{algorithm.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AlgorithmQuery) OnlyX(ctx context.Context) *Algorithm {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Algorithm ID in the query.
// Returns a *NotSingularError when more than one Algorithm ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AlgorithmQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{algorithm.Label}
	default:
		err = &NotSingularError{algorithm.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AlgorithmQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Algorithms.
func (aq *AlgorithmQuery) All(ctx context.Context) ([]*Algorithm, error) {
	ctx = setContextOp(ctx, aq.ctx, "All")
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Algorithm, *AlgorithmQuery]()
	return withInterceptors[[]*Algorithm](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AlgorithmQuery) AllX(ctx context.Context) []*Algorithm {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Algorithm IDs.
func (aq *AlgorithmQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, "IDs")
	if err = aq.Select(algorithm.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AlgorithmQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AlgorithmQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, "Count")
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AlgorithmQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AlgorithmQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AlgorithmQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, "Exist")
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AlgorithmQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlgorithmQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AlgorithmQuery) Clone() *AlgorithmQuery {
	if aq == nil {
		return nil
	}
	return &AlgorithmQuery{
		config:     aq.config,
		ctx:        aq.ctx.Clone(),
		order:      append([]algorithm.OrderOption{}, aq.order...),
		inters:     append([]Interceptor{}, aq.inters...),
		predicates: append([]predicate.Algorithm{}, aq.predicates...),
		withTasks:  aq.withTasks.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlgorithmQuery) WithTasks(opts ...func(*TaskQuery)) *AlgorithmQuery {
	query := (&TaskClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withTasks = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Algorithm.Query().
//		GroupBy(algorithm.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AlgorithmQuery) GroupBy(field string, fields ...string) *AlgorithmGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AlgorithmGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = algorithm.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Algorithm.Query().
//		Select(algorithm.FieldCreatedAt).
//		Scan(ctx, &v)
func (aq *AlgorithmQuery) Select(fields ...string) *AlgorithmSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AlgorithmSelect{AlgorithmQuery: aq}
	sbuild.label = algorithm.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AlgorithmSelect configured with the given aggregations.
func (aq *AlgorithmQuery) Aggregate(fns ...AggregateFunc) *AlgorithmSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AlgorithmQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !algorithm.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AlgorithmQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Algorithm, error) {
	var (
		nodes       = []*Algorithm{}
		_spec       = aq.querySpec()
		loadedTypes = [1]bool{
			aq.withTasks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Algorithm).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Algorithm{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(aq.modifiers) > 0 {
		_spec.Modifiers = aq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withTasks; query != nil {
		if err := aq.loadTasks(ctx, query, nodes,
			func(n *Algorithm) { n.Edges.Tasks = []*Task{} },
			func(n *Algorithm, e *Task) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AlgorithmQuery) loadTasks(ctx context.Context, query *TaskQuery, nodes []*Algorithm, init func(*Algorithm), assign func(*Algorithm, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Algorithm)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldAlgoID)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(algorithm.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AlgoID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "algo_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (aq *AlgorithmQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	if len(aq.modifiers) > 0 {
		_spec.Modifiers = aq.modifiers
	}
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AlgorithmQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(algorithm.Table, algorithm.Columns, sqlgraph.NewFieldSpec(algorithm.FieldID, field.TypeUint64))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, algorithm.FieldID)
		for i := range fields {
			if fields[i] != algorithm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AlgorithmQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(algorithm.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = algorithm.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range aq.modifiers {
		m(selector)
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (aq *AlgorithmQuery) ForUpdate(opts ...sql.LockOption) *AlgorithmQuery {
	if aq.driver.Dialect() == dialect.Postgres {
		aq.Unique(false)
	}
	aq.modifiers = append(aq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return aq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (aq *AlgorithmQuery) ForShare(opts ...sql.LockOption) *AlgorithmQuery {
	if aq.driver.Dialect() == dialect.Postgres {
		aq.Unique(false)
	}
	aq.modifiers = append(aq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return aq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aq *AlgorithmQuery) Modify(modifiers ...func(s *sql.Selector)) *AlgorithmSelect {
	aq.modifiers = append(aq.modifiers, modifiers...)
	return aq.Select()
}

// AlgorithmGroupBy is the group-by builder for Algorithm entities.
type AlgorithmGroupBy struct {
	selector
	build *AlgorithmQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AlgorithmGroupBy) Aggregate(fns ...AggregateFunc) *AlgorithmGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AlgorithmGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, "GroupBy")
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlgorithmQuery, *AlgorithmGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AlgorithmGroupBy) sqlScan(ctx context.Context, root *AlgorithmQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AlgorithmSelect is the builder for selecting fields of Algorithm entities.
type AlgorithmSelect struct {
	*AlgorithmQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AlgorithmSelect) Aggregate(fns ...AggregateFunc) *AlgorithmSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AlgorithmSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, "Select")
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AlgorithmQuery, *AlgorithmSelect](ctx, as.AlgorithmQuery, as, as.inters, v)
}

func (as *AlgorithmSelect) sqlScan(ctx context.Context, root *AlgorithmQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (as *AlgorithmSelect) Modify(modifiers ...func(s *sql.Selector)) *AlgorithmSelect {
	as.modifiers = append(as.modifiers, modifiers...)
	return as
}
