// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blues120/ias-core/data/ent/predicate"
	"github.com/blues120/ias-core/data/ent/warnpush"
)

// WarnPushQuery is the builder for querying WarnPush entities.
type WarnPushQuery struct {
	config
	ctx        *QueryContext
	order      []warnpush.OrderOption
	inters     []Interceptor
	predicates []predicate.WarnPush
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WarnPushQuery builder.
func (wpq *WarnPushQuery) Where(ps ...predicate.WarnPush) *WarnPushQuery {
	wpq.predicates = append(wpq.predicates, ps...)
	return wpq
}

// Limit the number of records to be returned by this query.
func (wpq *WarnPushQuery) Limit(limit int) *WarnPushQuery {
	wpq.ctx.Limit = &limit
	return wpq
}

// Offset to start from.
func (wpq *WarnPushQuery) Offset(offset int) *WarnPushQuery {
	wpq.ctx.Offset = &offset
	return wpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wpq *WarnPushQuery) Unique(unique bool) *WarnPushQuery {
	wpq.ctx.Unique = &unique
	return wpq
}

// Order specifies how the records should be ordered.
func (wpq *WarnPushQuery) Order(o ...warnpush.OrderOption) *WarnPushQuery {
	wpq.order = append(wpq.order, o...)
	return wpq
}

// First returns the first WarnPush entity from the query.
// Returns a *NotFoundError when no WarnPush was found.
func (wpq *WarnPushQuery) First(ctx context.Context) (*WarnPush, error) {
	nodes, err := wpq.Limit(1).All(setContextOp(ctx, wpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{warnpush.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wpq *WarnPushQuery) FirstX(ctx context.Context) *WarnPush {
	node, err := wpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WarnPush ID from the query.
// Returns a *NotFoundError when no WarnPush ID was found.
func (wpq *WarnPushQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = wpq.Limit(1).IDs(setContextOp(ctx, wpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{warnpush.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wpq *WarnPushQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := wpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WarnPush entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WarnPush entity is found.
// Returns a *NotFoundError when no WarnPush entities are found.
func (wpq *WarnPushQuery) Only(ctx context.Context) (*WarnPush, error) {
	nodes, err := wpq.Limit(2).All(setContextOp(ctx, wpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{warnpush.Label}
	default:
		return nil, &NotSingularError{warnpush.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wpq *WarnPushQuery) OnlyX(ctx context.Context) *WarnPush {
	node, err := wpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WarnPush ID in the query.
// Returns a *NotSingularError when more than one WarnPush ID is found.
// Returns a *NotFoundError when no entities are found.
func (wpq *WarnPushQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = wpq.Limit(2).IDs(setContextOp(ctx, wpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{warnpush.Label}
	default:
		err = &NotSingularError{warnpush.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wpq *WarnPushQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := wpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WarnPushes.
func (wpq *WarnPushQuery) All(ctx context.Context) ([]*WarnPush, error) {
	ctx = setContextOp(ctx, wpq.ctx, "All")
	if err := wpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WarnPush, *WarnPushQuery]()
	return withInterceptors[[]*WarnPush](ctx, wpq, qr, wpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wpq *WarnPushQuery) AllX(ctx context.Context) []*WarnPush {
	nodes, err := wpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WarnPush IDs.
func (wpq *WarnPushQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if wpq.ctx.Unique == nil && wpq.path != nil {
		wpq.Unique(true)
	}
	ctx = setContextOp(ctx, wpq.ctx, "IDs")
	if err = wpq.Select(warnpush.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wpq *WarnPushQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := wpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wpq *WarnPushQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wpq.ctx, "Count")
	if err := wpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wpq, querierCount[*WarnPushQuery](), wpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wpq *WarnPushQuery) CountX(ctx context.Context) int {
	count, err := wpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wpq *WarnPushQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wpq.ctx, "Exist")
	switch _, err := wpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wpq *WarnPushQuery) ExistX(ctx context.Context) bool {
	exist, err := wpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WarnPushQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wpq *WarnPushQuery) Clone() *WarnPushQuery {
	if wpq == nil {
		return nil
	}
	return &WarnPushQuery{
		config:     wpq.config,
		ctx:        wpq.ctx.Clone(),
		order:      append([]warnpush.OrderOption{}, wpq.order...),
		inters:     append([]Interceptor{}, wpq.inters...),
		predicates: append([]predicate.WarnPush{}, wpq.predicates...),
		// clone intermediate query.
		sql:  wpq.sql.Clone(),
		path: wpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WarnPush.Query().
//		GroupBy(warnpush.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wpq *WarnPushQuery) GroupBy(field string, fields ...string) *WarnPushGroupBy {
	wpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WarnPushGroupBy{build: wpq}
	grbuild.flds = &wpq.ctx.Fields
	grbuild.label = warnpush.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WarnPush.Query().
//		Select(warnpush.FieldCreatedAt).
//		Scan(ctx, &v)
func (wpq *WarnPushQuery) Select(fields ...string) *WarnPushSelect {
	wpq.ctx.Fields = append(wpq.ctx.Fields, fields...)
	sbuild := &WarnPushSelect{WarnPushQuery: wpq}
	sbuild.label = warnpush.Label
	sbuild.flds, sbuild.scan = &wpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WarnPushSelect configured with the given aggregations.
func (wpq *WarnPushQuery) Aggregate(fns ...AggregateFunc) *WarnPushSelect {
	return wpq.Select().Aggregate(fns...)
}

func (wpq *WarnPushQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wpq); err != nil {
				return err
			}
		}
	}
	for _, f := range wpq.ctx.Fields {
		if !warnpush.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wpq.path != nil {
		prev, err := wpq.path(ctx)
		if err != nil {
			return err
		}
		wpq.sql = prev
	}
	return nil
}

func (wpq *WarnPushQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WarnPush, error) {
	var (
		nodes = []*WarnPush{}
		_spec = wpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WarnPush).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WarnPush{config: wpq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(wpq.modifiers) > 0 {
		_spec.Modifiers = wpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wpq *WarnPushQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wpq.querySpec()
	if len(wpq.modifiers) > 0 {
		_spec.Modifiers = wpq.modifiers
	}
	_spec.Node.Columns = wpq.ctx.Fields
	if len(wpq.ctx.Fields) > 0 {
		_spec.Unique = wpq.ctx.Unique != nil && *wpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wpq.driver, _spec)
}

func (wpq *WarnPushQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(warnpush.Table, warnpush.Columns, sqlgraph.NewFieldSpec(warnpush.FieldID, field.TypeUint64))
	_spec.From = wpq.sql
	if unique := wpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wpq.path != nil {
		_spec.Unique = true
	}
	if fields := wpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, warnpush.FieldID)
		for i := range fields {
			if fields[i] != warnpush.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wpq *WarnPushQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wpq.driver.Dialect())
	t1 := builder.Table(warnpush.Table)
	columns := wpq.ctx.Fields
	if len(columns) == 0 {
		columns = warnpush.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wpq.sql != nil {
		selector = wpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wpq.ctx.Unique != nil && *wpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range wpq.modifiers {
		m(selector)
	}
	for _, p := range wpq.predicates {
		p(selector)
	}
	for _, p := range wpq.order {
		p(selector)
	}
	if offset := wpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (wpq *WarnPushQuery) ForUpdate(opts ...sql.LockOption) *WarnPushQuery {
	if wpq.driver.Dialect() == dialect.Postgres {
		wpq.Unique(false)
	}
	wpq.modifiers = append(wpq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return wpq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (wpq *WarnPushQuery) ForShare(opts ...sql.LockOption) *WarnPushQuery {
	if wpq.driver.Dialect() == dialect.Postgres {
		wpq.Unique(false)
	}
	wpq.modifiers = append(wpq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return wpq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (wpq *WarnPushQuery) Modify(modifiers ...func(s *sql.Selector)) *WarnPushSelect {
	wpq.modifiers = append(wpq.modifiers, modifiers...)
	return wpq.Select()
}

// WarnPushGroupBy is the group-by builder for WarnPush entities.
type WarnPushGroupBy struct {
	selector
	build *WarnPushQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wpgb *WarnPushGroupBy) Aggregate(fns ...AggregateFunc) *WarnPushGroupBy {
	wpgb.fns = append(wpgb.fns, fns...)
	return wpgb
}

// Scan applies the selector query and scans the result into the given value.
func (wpgb *WarnPushGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wpgb.build.ctx, "GroupBy")
	if err := wpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WarnPushQuery, *WarnPushGroupBy](ctx, wpgb.build, wpgb, wpgb.build.inters, v)
}

func (wpgb *WarnPushGroupBy) sqlScan(ctx context.Context, root *WarnPushQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wpgb.fns))
	for _, fn := range wpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wpgb.flds)+len(wpgb.fns))
		for _, f := range *wpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WarnPushSelect is the builder for selecting fields of WarnPush entities.
type WarnPushSelect struct {
	*WarnPushQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wps *WarnPushSelect) Aggregate(fns ...AggregateFunc) *WarnPushSelect {
	wps.fns = append(wps.fns, fns...)
	return wps
}

// Scan applies the selector query and scans the result into the given value.
func (wps *WarnPushSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wps.ctx, "Select")
	if err := wps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WarnPushQuery, *WarnPushSelect](ctx, wps.WarnPushQuery, wps, wps.inters, v)
}

func (wps *WarnPushSelect) sqlScan(ctx context.Context, root *WarnPushQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wps.fns))
	for _, fn := range wps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (wps *WarnPushSelect) Modify(modifiers ...func(s *sql.Selector)) *WarnPushSelect {
	wps.modifiers = append(wps.modifiers, modifiers...)
	return wps
}
